### model
model_name_or_path: /mnt/fr20tb/sanghyuk/workspace/models/hcx-jessica-seorak-vocexp
flash_attn: fa2
enable_liger_kernel: true

### method
stage: speechx
do_train: true
finetuning_type: full
deepspeed: /mnt/fr20tb/sanghyuk/workspace/LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
compute_accuracy: false
report_to: [tensorboard, wandb]

### dataset
dataset: speechx_v6 # 의미 없음
speechx_dataset:
  - 
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/audio_len_2.5_asr', 0.1]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/audio_len_2.5_continue', 0.2]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/audio_len_2.5_tts', 0.1]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/sentence_asr', 0.1]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/sentence_tts', 0.1]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/word_asr', 0.1]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/word_continue', 0.2]
    - ['/mnt/ddn/audiollm/soyoon/interleaving/train/v5_datasets/datasets/word_tts', 0.1]
  - /mnt/ddn/audiollm/soyoon/interleaving/train/v6_datasets/datasets/unsupervised/audio_clip_units_idx_split_4096

speechx_tokenized_path: 
  - '/mnt/tmp/v6_interleave_packed'
  - '/mnt/tmp/v6_audioclip_packed'
 
speechx_dataset_ratios: [3, 1]

### eval_dataset
eval_dataset:
  hcx_text_only: /mnt/fr20tb/audiollm/datasets/testset/hcx_textonly
  librispeech-test-clean: /mnt/fr20tb/audiollm/datasets/testset/librispeech_test_clean
  librispeech-test-other: /mnt/fr20tb/audiollm/datasets/testset/librispeech_test_other
  ksponspeech-eval-clean: /mnt/fr20tb/audiollm/datasets/testset/ksponspeech_eval_clean
  ksponspeech-eval-other: /mnt/fr20tb/audiollm/datasets/testset/ksponspeech_eval_other
  ksponspeech-eval-clean-asr: /mnt/fr20tb/audiollm/datasets/testset/ksponspeech_eval_clean_asr
  ksponspeech-eval-clean-tts: /mnt/fr20tb/audiollm/datasets/testset/ksponspeech_eval_clean_tts
  librispeech-test-clean-asr: /mnt/fr20tb/audiollm/datasets/testset/librispeech_test_clean_asr
  librispeech-test-clean-tts: /mnt/fr20tb/audiollm/datasets/testset/librispeech_test_clean_tts

eval_tokenized_path: '/mnt/tmp/eval_packed/hcx_text_only'

template: speechx # 의미 없음
cutoff_len: 4096
overwrite_cache: false
preprocessing_num_workers: 32
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true

### output
output_dir: /mnt/tmp/results  # 하위에 run_name 디렉터리 안에 저장됨
logging_dir: /mnt/fr20tb/audiollm/sanghyuk/results_abl  # tensorboard log 저장 위치
logging_steps: 50
save_steps: 500
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
weight_decay: 0.0
# num_train_epochs: 1.0
max_steps: 8500
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
  num_stable_steps: 8000
  num_decay_steps: 500

warmup_steps: 0
resume_from_checkpoint: true

bf16: true
ddp_timeout: 180000000
dataloader_prefetch_factor: 2
dataloader_num_workers: 8

### eval
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 100
