### model
model_name_or_path: /mnt/fr20tb/sanghyuk/workspace/models/SpeechX_v7_Stage2_65000_v3
flash_attn: fa2
enable_liger_kernel: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed:  /mnt/fr20tb/sanghyuk/workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
report_to: [tensorboard, wandb]

### dataset
dataset_dir: /mnt/fr20tb/audiollm/sanghyuk/datasets/streaming_ve_v7
dataset: spk, non_spk
template: speechx_empty
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 32
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true
tokenized_path: /mnt/fr20tb/audiollm/sanghyuk/v7_streaming_ve_packed

### output
run_name: streaming_ve_v7_cand5
output_dir: /mnt/audiodata/results  # 하위에 run_name 디렉터리 안에 저장됨
logging_dir: /mnt/audiodata/results  # tensorboard log 저장 위치
logging_strategy: steps    # logging은 step 단위 유지해도 무방
logging_steps: 5           # 3~10 정도로 자주 기록
plot_loss: false
overwrite_output_dir: true
save_total_limit: 8
save_strategy: epoch
save_only_model: true
load_best_model_at_end: false

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.25
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01
dataloader_prefetch_factor: 4
dataloader_num_workers: 8
dataloader_persistent_workers: false
# resume_from_checkpoint: true

### eval
val_size: 0.025
per_device_eval_batch_size: 2
eval_strategy: epoch
# eval_steps: 50
