### model
model_name_or_path: /mnt/tmp/models/helsinki

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: /home/nsml/workspace/LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: /mnt/tmp/dataset
dataset: sc_data,press_data
template: speechx_empty
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 3
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true
tokenized_path: /mnt/tmp/packed_data/sc_press

### output
output_dir: /mnt/tmp/results
logging_dir: /mnt/tmp/results
logging_steps: 5
save_steps: 40
plot_loss: false
overwrite_output_dir: true
save_total_limit: 2
save_strategy: steps
load_best_model_at_end: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 4.0e-5
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.001
dataloader_prefetch_factor: 2
dataloader_num_workers: 8
dataloader_persistent_workers: false
resume_from_checkpoint: false

## lora
lora_rank: 128

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10

## additional configs
flash_attn: fa2
enable_liger_kernel: false
