### model
model_name_or_path: /mnt/fr20tb/audiollm/sanghyuk/results/Speechx_v7_4B_stage1/checkpoint-15000
flash_attn: fa2
enable_liger_kernel: true

### method
stage: speechx
do_train: true
do_eval: false
finetuning_type: full
deepspeed: /mnt/fr20tb/sanghyuk/workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
compute_accuracy: false
report_to: [tensorboard, wandb]

### dataset
dataset: speechx_v7 # 의미 없음
speechx_dataset:
  - '/mnt/fr20tb/audiollm/sanghyuk/v7_textonly_tokenized'

speechx_tokenized_path: 
  - '/mnt/fr20tb/audiollm/sanghyuk/v7_textonly_packed'
 
speechx_dataset_ratios: [1]

template: speechx # 의미 없음
cutoff_len: 4096
overwrite_cache: false
preprocessing_num_workers: 32
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true

### output
run_name: Speechx_v7_4B_stage2_onlytext
output_dir: /mnt/audiodata/results  # 하위에 run_name 디렉터리 안에 저장됨
logging_dir: /mnt/audiodata/results  # tensorboard log 저장 위치
logging_steps: 50
save_steps: 1000
save_total_limit: 5
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
weight_decay: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: warmup_stable_decay
warmup_steps: 1500
bf16: true
ddp_timeout: 180000000

### eval
eval_strategy: 'no'
per_device_eval_batch_size: 1
eval_steps: 0
