### model
model_name_or_path: /mnt/fr20tb/audiollm/voice_model/models/voice_engine_v6_abl3-a

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
report_to: [tensorboard, wandb]

### dataset
dataset_dir: /mnt/fr20tb/audiollm/sanghyuk/datasets/voice_engine_v6_abl3
dataset: v6_abl3-l_voice_engine
template: speechx_empty
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 4
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true
tokenized_path: /mnt/fr20tb/audiollm/voice_model/packed_data/250717_voice_engine_v6_abl3-l_sft
### output
output_dir: /mnt/fr20tb/audiollm/voice_model/models
logging_dir: /mnt/fr20tb/audiollm/voice_model/results
logging_strategy: steps    # logging은 step 단위 유지해도 무방
logging_steps: 5           # 3~10 정도로 자주 기록
plot_loss: false
overwrite_output_dir: true
save_total_limit: 5
save_strategy: epoch
save_only_model: true

load_best_model_at_end: false

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.20
bf16: true
ddp_timeout: 180000000
weight_decay: 0.001
dataloader_prefetch_factor: 2
dataloader_num_workers: 8
dataloader_persistent_workers: false
# resume_from_checkpoint: true

### eval
val_size: 0.04
per_device_eval_batch_size: 2
eval_strategy: epoch
# eval_steps: 50

## additional configs
flash_attn: fa2
enable_liger_kernel: true

token_weights:
  - token: "<|im_end|>"
    weight: 3.6
  - token: "<|endofturn|>"
    weight: 3.6