### model
model_name_or_path: /mnt/fr20tb/audiollm/voice_model/models/voice_model_v5/checkpoint-29500

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
report_to: [tensorboard, wandb]

### dataset
dataset: v5_voice_engine
template: speechx_empty
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true
tokenized_path: /mnt/fr20tb/audiollm/voice_model/packed_data/250328_voice_engine_v5_sft
### output
output_dir: /mnt/fr20tb/audiollm/voice_model/models
logging_dir: /mnt/fr20tb/audiollm/voice_model/results
logging_steps: 20
save_steps: 100
plot_loss: false
overwrite_output_dir: true
save_total_limit: 3
save_strategy: steps
load_best_model_at_end: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.001
dataloader_prefetch_factor: 2
dataloader_num_workers: 8
dataloader_persistent_workers: false
# resume_from_checkpoint: true

## lora
lora_rank: 128

### eval
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50

## additional configs
flash_attn: fa2
enable_liger_kernel: true