### model
model_name_or_path: /mnt/fr20tb/audiollm/sanghyuk/results/models/v4_jessica_high_lr/checkpoint-33207 #meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
report_to: [tensorboard, wandb]

### dataset
dataset: asr_sft
template: speechx
cutoff_len: 4096
overwrite_cache: false
preprocessing_num_workers: 16
streaming: false
packing: true
neat_packing: true
preprocessing_batch_size: 2048
predict_with_generate: false
dataloader_pin_memory: true
accelerator_config:
  split_batches: false
  dispatch_batches: false
  non_blocking: true

tokenized_path: /mnt/fr20tb/audiollm/soyoon/packed_data/asr_20250224_all_0.1
### output
output_dir: /mnt/fr20tb/audiollm/soyoon/models
logging_dir: /mnt/fr20tb/audiollm/soyoon/results
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.001
## lora
lora_rank: 256

### eval
val_size: 0.005
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
